import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import './globals.css';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="html">
      <body className={`${montserrat.className} antialiased bg-white text-black dark:bg-black dark:text-white`}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
